### Array Creations

In [4]:
# 1. Simple Array Creation
import numpy as np 
a = np.array([10, 20 , 30 , 40])
a

array([10, 20, 30, 40])

In [6]:
type(a)

numpy.ndarray

In [12]:
# 2. 2D Array Creation
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
# 3. Some Shortcut Arrays
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((2,4)) 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.eye(3) # identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.arange(0,10,2) # range from 0 to 10 with a gap of 2 numbers.

array([0, 2, 4, 6, 8])

In [30]:
np.linspace(0,1,5) # a matrix which starts from 0 and end at 1 and adjust into 5 number with equal diff.

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Array's properties

In [35]:
arr = np.array([[1,2,3],[4,5,6]])

In [41]:
arr.shape # shape of array 2 rows , 3 columns

(2, 3)

In [43]:
arr.ndim # dimensions

2

In [45]:
arr.size # total 6 elements

6

In [49]:
arr.dtype # data type of array

dtype('int32')

### Slicing in array

In [56]:
arr[0] # becoz it treats each row as single elment in 2d array 

array([1, 2, 3])

In [58]:
arr[0,0] # thats how u can get very first element 

1

In [64]:
arr[-1,-1] # to get very last elements

6

In [68]:
arr[-1,2] # u gonna get same result as above just diff methods

6

In [78]:
arr[:1] # it will return row 0 to 1(excluded) shape 2D

array([[1, 2, 3]])

In [80]:
arr[0] # it will also retuyrn the 0th row but shape is 1D

array([1, 2, 3])

In [86]:
arr[0:2,1:] # so before comma are rows 0 to 2(excluded) so 0 and 1 rows ,,, after comma columns 1 to end

array([[2, 3],
       [5, 6]])

### Arthematic operations

In [89]:
c = np.array([1 , 2 , 3])
d = np.array([10 , 20 , 30])

In [91]:
c+d

array([11, 22, 33])

In [93]:
c-d

array([ -9, -18, -27])

In [95]:
c*d

array([10, 40, 90])

In [97]:
c/d

array([0.1, 0.1, 0.1])

In [99]:
c**2

array([1, 4, 9])

In [103]:
c+10 # broadcasting

array([11, 12, 13])

### Reshaping

In [108]:
H = np.arange(1,13) # 1 to 13(excluded)
H

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [114]:
h = H.reshape(3,4) # u can reshape but with feasible size i.e. 3x4 = 12.
h

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [116]:
# if u don't know how to make a practical size ffrom given range use '-1' 
H.reshape(3,-1) # for columns

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [118]:
H.reshape(-1,4) # for rows

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [120]:
H.reshape(-1) # flat 1D array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [124]:
f = h.flatten() # it makes copy of array
f

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [128]:
E = h.ravel() # it makes view of array
E 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [132]:
Q = np.array([[2,3,5],[3,7,8]])
Q

array([[2, 3, 5],
       [3, 7, 8]])

In [138]:
Q.shape

(2, 3)

In [136]:
t = Q.T  # transpose
t

array([[2, 3],
       [3, 7],
       [5, 8]])

In [140]:
t.shape

(3, 2)

In [152]:
Q = np.expand_dims(arr,axis = 0) # it added one more dimension in a 2D array
Q  # axis 0 for row vector and axis 1 for column vector

array([[[1, 2, 3],
        [4, 5, 6]]])

In [148]:
Q.shape # now its 3 dimensional with 1 layer , 2 rows and 3 columns.

(1, 2, 3)

### Mathematical Functions

##### Aggregate Functions

In [158]:
W = np.array([[1,2,3],[4,5,6]])
W

array([[1, 2, 3],
       [4, 5, 6]])

In [162]:
np.sum(W) # complete element sum

21

In [166]:
np.sum(W,axis = 0) # columns wise sum

array([5, 7, 9])

In [168]:
np.sum(W,axis = 1) # row wise sum

array([ 6, 15])

In [170]:
np.mean(W)

3.5

In [173]:
np.mean(W,axis = 0) # column wise mean

array([2.5, 3.5, 4.5])

In [177]:
np.argmin(W) # min value ka index

0

In [179]:
np.argmax(W) # max value ka index

5

##### Statstical Functions

In [186]:
data = np.array([2,4,5,4,5,6,5,7,9])
data

array([2, 4, 5, 4, 5, 6, 5, 7, 9])

In [196]:
np.std(data) # standard deviation

1.8724777273725242

In [198]:
np.var(data) # variance

3.506172839506173

In [194]:
np.median(data)

5.0

In [202]:
np.percentile(data,75) # 75th percentile

6.0

##### Normalization

In [205]:
arr = np.array([10, 20, 30, 40, 50], dtype=float)

In [209]:
# min-max normalization to get the data in between 0 and 1
normalized = (arr-np.min(arr))/(np.max(arr)-np.min(arr))
normalized

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [211]:
# Standardization (mean=0, std=1)
standardized = (arr - np.mean(arr)) / np.std(arr)
standardized

array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

##### Dot product and Matrix multiplication

In [214]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.dot(a, b)       # 32 → (1×4 + 2×5 + 3×6)

32

In [216]:
# Matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(A @ B)  

[[19 22]
 [43 50]]


##### Comparison and Boolean operations

In [221]:
arr1 = np.array([1, 5, 3, 8, 2, 9])
arr1 > 4         # [F T F T F T] → boolean array


array([False,  True, False,  True, False,  True])

In [225]:
print(arr1[arr1 > 4])      # [5 8 9] → only those  elements which satisfy the condition ( only true elements)

[5 8 9]


In [227]:
# use in ML
predictions = np.array([0.2, 0.8, 0.6, 0.3])
labels = (predictions > 0.5).astype(int)
labels  # [0 1 1 0] → thresholding!

array([0, 1, 1, 0])